site_name: Freetribe Documentation
site_url: https://bangcorrupt.github.io/freetribe-docs

nav:
  - index.md
  - features.md
  - getting-started.md
  - support.md
  - acknowledgements.md
  - license.md

plugins:
  - search

theme:
  name: material

  features:
    - search.suggest
    - search.highlight

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
